<h3>Documentation</h3>

Documentation available:
<ol>
    <li><a href="/cgi-pub/eareyan/documentation/download/file/milestone1">Milestone 1</a>, delivered on September 23, 2011</li>
    <li>Milestone 2, to be deliver on October 19, 2011</li>
    <ul>
        <li><a href="/cgi-pub/eareyan/documentation/download/file/milestone2">Document</a></li>
        <li><a href="/cgi-pub/eareyan/documentation/download/file/milestone2-presentation">Milestone 2 Presentation</a></li>
        <li><a href="/cgi-pub/eareyan/documentation/download/file/milestone2-revision1">First Revision of the Document</a>, October 10</li>
    </ul>
</ol>